# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 14
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
  - bug
  - EPIC
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs.

  Thank you for your contributions.

  We are doing this to be sure that the issue is still relevant.
  Anyone can comment to remove the stale state.
  (The issues marked with `pinned`, `security`, `bug` or `EPIC` label
   are not considered stale.)
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
