---
specfile_path: packit.spec
synced_files:
  - packit.spec
  - .packit.yaml
  - src: fedora-tests/
    dest: tests/
# packit was already taken on PyPI
upstream_project_name: packitos
downstream_package_name: packit
current_version_command: ["python3", "setup.py", "--version"]
create_tarball_command: ["python3", "setup.py", "sdist", "--dist-dir", "."]
jobs:
- job: propose_downstream
  trigger: release
  metadata:
    dist_git_branch: master
- job: propose_downstream
  trigger: release
  metadata:
    dist_git_branch: f30
- job: propose_downstream
  trigger: release
  metadata:
    dist_git_branch: f29
- job: sync_from_downstream
  trigger: commit
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
    - fedora-29-x86_64
    - fedora-rawhide-x86_64
    - fedora-30-x86_64
