---
specfile_path: packit.spec
synced_files:
  - packit.spec
  - .packit.yaml
  - src: fedora-tests/
    dest: tests/
# packit was already taken on PyPI
upstream_package_name: packitos
# backwards compat
upstream_project_name: packitos
downstream_package_name: packit
upstream_project_url: https://github.com/packit-service/packit
current_version_command: ["python3", "setup.py", "--version"]
create_tarball_command: ["python3", "setup.py", "sdist", "--dist-dir", "."]
create_pr: false
jobs:
- job: propose_downstream
  trigger: release
  metadata:
    dist-git-branch: master
- job: propose_downstream
  trigger: release
  metadata:
    dist-git-branch: f30
- job: propose_downstream
  trigger: release
  metadata:
    dist-git-branch: f29
- job: sync_from_downstream
  trigger: commit
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
    - fedora-29-x86_64
    - fedora-30-x86_64
    - fedora-31-x86_64
    - fedora-rawhide-x86_64  # no compose for a week+, let's have ticks in our PRs
