---
# We want to use both instances for all upstream jobs including the `propose-downstream` one.
# For downstream, we need to pick just one instance (`stg` in our case)
# and redefine it for the `koji_build` and `bodhi_update` jobs.
packit_instances: ["prod", "stg"]

packages:
  packit:
    downstream_package_name: packit
    # packit was already taken on PyPI
    upstream_package_name: packitos
    upstream_project_url: https://github.com/packit/packit
    paths:
      - ./
    specfile_path: packit.spec
    files_to_sync:
      - packit.spec
      - .packit.yaml
      - src: plans/
        dest: plans/
      - src: .fmf/
        dest: .fmf/

version_update_mask: '\d+\.'

copy_upstream_release_description: true
issue_repository: https://github.com/packit/packit

actions:
  create-archive:
    - "python3 -m build --sdist --outdir ."
    - "sh -c 'echo packitos-$(hatch version).tar.gz'"
  get-current-version:
    - "hatch version"
  pre-sync:
    # FMF has to be installed on system where you are calling this tool.
    - python3 plans/git_reference.py

allowed_gpg_keys:
  - 5DE3E0509C47EA3CF04A42D34AEE18F83AFDEB23

srpm_build_deps:
  - python3-build
  - hatch
  - python3-hatch-vcs

jobs:
  - job: propose_downstream
    trigger: release
    # Use the stage instance once it works in downstream.
    dist_git_branches:
      rawhide:
        fast_forward_merge_into: [fedora-branched]

  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all
      - fedora-all-aarch64
    packages:
      - packit

  - job: tests
    trigger: pull_request
    targets:
      - fedora-all
    packages:
      - packit

  - job: copr_build
    trigger: commit
    branch: main
    targets:
      - fedora-all
      - fedora-all-aarch64
    project: packit-dev
    list_on_homepage: True
    preserve_project: True

  - job: copr_build
    trigger: commit
    branch: stable
    targets:
      - fedora-latest-stable
      - fedora-latest-stable-aarch64
    project: packit-stable
    list_on_homepage: True
    preserve_project: True

  - job: copr_build
    trigger: release
    targets:
      - fedora-stable
      - fedora-stable-aarch64
    project: packit-releases
    list_on_homepage: True
    preserve_project: True

  # downstream automation:
  - job: pull_from_upstream
    trigger: release
    dist_git_branches:
      rawhide:
        fast_forward_merge_into: [fedora-branched]

  - job: koji_build
    trigger: commit | koji_build
    packit_instances: ["stg"]
    allowed_pr_authors: ["packit-stg", "packit"]
    sidetag_group: packit-specfile-ogr-releases
    dependencies:
      - python-ogr
      - python-specfile
    dist_git_branches:
      - fedora-all

  - job: bodhi_update
    trigger: koji_build
    packit_instances: ["stg"]
    allowed_builders: ["packit-stg", "packit"]
    sidetag_group: packit-specfile-ogr-releases
    dependencies:
      - python-ogr
      - python-specfile
    dist_git_branches:
      - fedora-all
#  - job: vm_image_build
#    trigger: pull_request
#    packit_instances: ["stg"]
#    image_distribution: rhel-8
#    image_type: aws
#    image_architecture: x86_64
#    image_account_id: "727920394381"
#    packages_to_install: [packit]
#    owner: packit
#    project: packit-dev
#    targets: [epel-8]
