---
synced_files:
  - src: fedora-tests/
    dest: tests/
# packit was already taken on PyPI
upstream_package_name: packitos
upstream_project_url: https://github.com/packit/packit
copy_upstream_release_description: true

actions:
  create-archive:
    - "python3 setup.py sdist --dist-dir ."
    - "sh -c 'echo packitos-$(python3 setup.py --version).tar.gz'"
  get-current-version:
    - "python3 setup.py --version"

jobs:
  - job: propose_downstream
    trigger: release
    metadata:
      dist_git_branches: fedora-all
  - job: sync_from_downstream
    trigger: commit
  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
        - fedora-all
  - job: tests
    trigger: pull_request
    metadata:
      targets:
        - fedora-stable # on rawhide we have problems with the new marshmallow
  - job: copr_build
    trigger: commit
    metadata:
      branch: master
      targets:
        - fedora-stable
      project: packit-master
      list_on_homepage: True
      preserve_project: True
  - job: copr_build
    trigger: release
    metadata:
      targets:
        - fedora-stable
      project: packit-releases
      list_on_homepage: True
      preserve_project: True
