---
# We want to use both instances for all upstream jobs including the `propose-downstream` one.
# For downstream, we need to pick just one instance (`stg` in our case)
# and redefine it for the `koji_build` and `bodhi_update` jobs.
packit_instances: ["prod", "stg"]
files_to_sync:
  - packit.spec
  - .packit.yaml
  - src: plans/
    dest: plans/
  - src: .fmf/
    dest: .fmf/
# packit was already taken on PyPI
upstream_package_name: packitos
upstream_project_url: https://github.com/packit/packit
copy_upstream_release_description: true
issue_repository: https://github.com/packit/packit

actions:
  create-archive:
    - "python3 setup.py sdist --dist-dir ."
    - "sh -c 'echo packitos-$(python3 setup.py --version).tar.gz'"
  get-current-version:
    - "python3 setup.py --version"
  pre-sync:
    # FMF has to be installed on system where you are calling this tool.
    - python3 plans/git_reference.py

allowed_gpg_keys:
  - 5DE3E0509C47EA3CF04A42D34AEE18F83AFDEB23

srpm_build_deps:
  - python3-pip # "python3 setup.py --version" needs it
  - python3-setuptools_scm

jobs:
  - job: propose_downstream
    trigger: release
    # Use the stage instance once it works in downstream.
    dist_git_branches:
      - fedora-all
      - epel-9

  - job: sync_from_downstream
    trigger: commit

  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all
      - epel-9
  - job: tests
    trigger: pull_request
    targets:
      - fedora-all
      - epel-9

  - job: copr_build
    trigger: commit
    branch: main
    targets:
      - fedora-all
      - epel-9
    project: packit-dev
    list_on_homepage: True
    preserve_project: True

  - job: copr_build
    trigger: commit
    branch: stable
    targets:
      - fedora-stable
      - epel-9
    project: packit-stable
    list_on_homepage: True
    preserve_project: True

  - job: copr_build
    trigger: release
    targets:
      - fedora-stable
      - epel-9
    project: packit-releases
    list_on_homepage: True
    preserve_project: True

  - job: pull_from_upstream
    trigger: release
    dist_git_branches:
      - fedora-all
      - epel-9

  # downstream automation:
  - job: koji_build
    trigger: commit
    packit_instances: ["stg"]
    allowed_pr_authors: ["packit-stg", "packit"]
    dist_git_branches:
      - fedora-all
      - epel-9

  - job: bodhi_update
    trigger: commit
    packit_instances: ["stg"]
    dist_git_branches:
      - fedora-branched
      - epel-9
#  - job: vm_image_build
#    trigger: pull_request
#    packit_instances: ["stg"]
#    image_distribution: rhel-8
#    image_type: aws
#    image_architecture: x86_64
#    image_account_id: "727920394381"
#    packages_to_install: [packit]
#    owner: packit
#    project: packit-dev
#    targets: [epel-8]
