---
specfile_path: packit.spec
synced_files:
  - packit.spec
  - .packit.yaml
  - src: fedora-tests/
    dest: tests/
# packit was already taken on PyPI
upstream_package_name: packitos
downstream_package_name: packit
upstream_project_url: https://github.com/packit-service/packit
current_version_command: ["python3", "setup.py", "--version"]
create_tarball_command: ["python3", "setup.py", "sdist", "--dist-dir", "."]
create_pr: false
jobs:
- job: propose_downstream
  trigger: release
  metadata:
    dist-git-branch: fedora-all
- job: sync_from_downstream
  trigger: commit
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
    - fedora-all
- job: tests
  trigger: pull_request
  metadata:
    targets:
    - fedora-stable # on rawhide we have problems with the new marshmallow
