---
- project:
    check:
      jobs:
        - pre-commit
        - packit-tests-rpm
        - packit-tests-pip-deps
        - packit-tests-git-main
        - packit-tests-rpm-sess-rec
        - packit-tests-pip-deps-sess-rec
        - packit-tests-git-main-sess-rec
        - reverse-dep-packit-service-tests
    gate:
      jobs:
        - pre-commit

- job:
    name: packit-tests-rpm
    parent: base
    description: Run tests with dependencies installed as RPMs
    pre-run: files/install-requirements-rpms.yaml
    run: files/zuul-tests.yaml

- job:
    name: packit-tests-pip-deps
    parent: base
    description: Run tests with dependencies installed from PyPI
    pre-run: files/install-requirements-pip.yaml
    run: files/zuul-tests.yaml

- job:
    name: packit-tests-git-main
    parent: base
    description: Run tests with dependencies installed from git main & PyPI
    pre-run: files/install-requirements-git.yaml
    run: files/zuul-tests.yaml

- job:
    name: reverse-dep-packit-service-tests
    parent: packit-tests-rpm
    description: Run packit-service tests to check we don't break it
    required-projects:
      - github.com/packit/packit-service
    run: files/zuul-reverse-dep-packit-service.yaml

- job:
    name: packit-tests-pip-deps-sess-rec
    parent: packit-tests-pip-deps
    description: Run session recording tests of packit with deps from PyPI
    run: files/zuul-tests-session-recording.yaml

- job:
    name: packit-tests-git-main-sess-rec
    parent: packit-tests-git-main
    description: Run session recording tests of packit with deps from git main & PyPI
    run: files/zuul-tests-session-recording.yaml

- job:
    name: reverse-dep-packit-service-tests
    parent: packit-tests-rpm
    description: Run packit-service tests to check we don't break it
    required-projects:
      - github.com/packit/packit-service
    run: files/zuul-reverse-dep-packit-service.yaml
