# This is the deployment playbook.
#
# If you need a debugger, I suggest to:
# 1. Change the command to bash
# 2. Run this playbook
# 3. sudo podman attach {syncer,watcher} bash
# 4. Insert ipdb probes in the code and run packit:
#   $ packit -d watch-pr --updated 2019-e693608f-d77c-41ab-8b2b-99825b6170f4
# Good luck!
---
- name: Deploy source-git
  hosts: all
  become: true
  tasks:
  - name: Gracefully remove syncer and watcher
    command: podman rm -f watcher syncer
    ignore_errors: true
  - name: Run watcher locally
    command: podman run -d --name watcher \
              -e GITHUB_TOKEN={{ github_token }} \
              -e PAGURE_PACKAGE_TOKEN={{ pagure_package_token }} \
              -e PAGURE_USER_TOKEN={{ pagure_user_token }} \
              -e PAGURE_FORK_TOKEN={{ pagure_fork_token }} \
              -e PYTHONPATH=/src \
              -v {{ playbook_dir }}:/src:Z \
              -w /src \
              -ti \
              {{ source_git_image }} \
              packit -d watch-fedora-ci
  - name: Run syncer locally
    command: podman run -d --name syncer \
              -e GITHUB_TOKEN={{ github_token }} \
              -e PAGURE_PACKAGE_TOKEN={{ pagure_package_token }} \
              -e PAGURE_USER_TOKEN={{ pagure_user_token }} \
              -e PAGURE_FORK_TOKEN={{ pagure_fork_token }} \
              -e PYTHONPATH=/src \
              -v {{ playbook_dir }}:/src:Z \
              -w /src \
              -ti \
              {{ source_git_image }} \
              packit -d watch-pr
