# Packit (test) dependencies.
# To run tests locally via 'make check_in_container'.

FROM fedora:31

RUN dnf -y install ansible

ENV ANSIBLE_PYTHON_INTERPRETER=/usr/bin/python3 \
    ANSIBLE_STDOUT_CALLBACK=debug

COPY files/tasks/*.yaml /files/tasks/
COPY files/*.yaml /files/
COPY *.spec .

RUN ansible-playbook -v -c local -i localhost, /files/install-build-deps.yaml
RUN ansible-playbook -v -c local -i localhost, /files/local-tests-requirements.yaml

WORKDIR /src
