---
- name: This is a recipe for a container image where packit tests will run
  hosts: all
  tasks:
  - name: Install all packages needed to run tests
    dnf:
      name:
      - python3-tox
      - python36
      - krb5-devel
      state: present
