---
- name: This is a recipe for how to cook with packit
  hosts: all
  vars:
    user_name: packit
    home_path: /home/{{ user_name }}
    ansible_bender:
      base_image: registry.fedoraproject.org/f29/httpd:2.4
      #base_image: fedora:29
      target_image:
        name: docker.io/usercont/packit-service
        environment:
          FLASK_APP: packit.service.web_hook
          LD_PRELOAD: libnss_wrapper.so
          NSS_WRAPPER_PASSWD: '{{ home_path }}/passwd'
          NSS_WRAPPER_GROUP: /etc/group
          USER: '{{ user_name }}'
          HOME: '{{ home_path }}'
        cmd: flask-3 run -h 0.0.0.0
      working_container:
        volumes:
        - '{{ playbook_dir }}:/src:Z'
  tasks:
  - user:
      name: '{{ user_name }}'
      create_home: yes
      home: '{{ home_path }}'
  - file:
      state: directory
      path: /home
      mode: 0777
      recurse: yes

  - copy:
      src: ./files/passwd
      dest: '{{ home_path }}/passwd'
      mode: 0777

  # Workaround for https://bodhi.fedoraproject.org/updates/FEDORA-2019-52487848d6
  - name: Remove /etc/httpd/state
    file:
      path: /etc/httpd/state
      state: absent
  # Workaround for https://bodhi.fedoraproject.org/updates/FEDORA-2019-52487848d6
  - name: Create link to /etc/httpd/state
    file:
      src: /var/lib/httpd
      dest: /etc/httpd/state
      state: link
  - name: Create /usr/share/packit directory
    file:
      state: directory
      path: /usr/share/packit
  - name: Copy packit.wsgi file
    copy:
      src: files/packit.wsgi
      dest: /usr/share/packit/packit.wsgi
      owner: apache
      group: apache
      mode: 0644

  - name: "Set up git: user.email"
    command: git config --global user.email "user-cont-team@redhat.com"
  - name: "Set up git: user.name"
    command: git config --global user.name "Pack It"
  - name: Create .ssh
    file:
      state: directory
      path: /root/.ssh
      mode: 0700
  - name: Copy ssh_config
    copy:
      src: files/ssh_config
      dest: /etc/ssh/ssh_config.d/01-packit.conf
  - name: stat /src
    stat:
      path: /src
    tags:
    - no-cache
    register: src_path
  - name: Let's make sure /src is present
    assert:
      that:
      - 'src_path.stat.isdir'
  - name: Install packit from /src
    pip:
      name: /src
      executable: pip3
