---
- name: Install generic RPM packages
  dnf:
    name:
      - make
      - git
      - dnf-utils
      - python3-pip
      - rpmdevtools
      - python3-bodhi-client
      - fedpkg
      - rsync
  become: true
