---
- ansible.builtin.set_fact:
    project_dir: "{{ playbook_dir }}/.."
  when: zuul is not defined
- ansible.builtin.set_fact:
    project_dir: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
  when: zuul is defined
- name: stat {{ project_dir }}
  ansible.builtin.stat:
    path: "{{ project_dir }}"
  tags:
    - no-cache
  register: src_path
- name: Assert project_dir is present
  ansible.builtin.assert:
    that:
      - src_path.stat.isdir
