---
- hosts: localhost
  roles:
    - role: standard-test-basic
      tags:
        - classic
      required_packages:
        - krb5-devel
        - make
        - python36
        - python3-devel
        - python3-flexmock
        - python3-packit
        - python3-pytest
        - python3-setuptools_scm
        - python3-setuptools_scm_git_archive
        - python3-tox
        - rpm-libs
        - redhat-rpm-config
      tests:
        - upstream:
            dir: .
            run: ./upstream.sh
        - simple_app:
            dir: .
            run: ./simple.py
