---
- name: Install RPM dependencies for packit
  hosts: all
  tasks:
    - ansible.builtin.include_tasks: tasks/project-dir.yaml
    - ansible.builtin.include_tasks: tasks/generic-dnf-requirements.yaml
    - ansible.builtin.include_tasks: tasks/build-rpm-deps.yaml
    - ansible.builtin.include_tasks: tasks/requre.yaml
