---
- name: Install dependencies for packit.
  hosts: all
  tasks:
  - name: Install generic RPM packages
    dnf:
      name:
      - make
      - git
      - dnf-utils
      - python3-pip

  - name: Install test rpm dependencies
    dnf:
      name:
      - python3-flexmock
      - python3-pytest
      - python3-pytest-cov
      state: present

  - name: Install runtime RPM deps
    dnf:
      name:
        - fedpkg
        - rpmdevtools
        - python3-bodhi-client
        - python3-cccolutils
        - rpmdevtools
      state: present

  - name: Install build RPM dependencies
    command: dnf -y builddep packit.spec

  - name: Pip install sandcastle, our sandboxing tech (needed when running as a service)
    pip:
      name: git+https://github.com/packit-service/sandcastle

  - name: Pip install pre-commit
    pip:
      name: pre-commit

  - name: "set up git: email"
    command: git config --global user.email test@example.com
  - name: "set up git: name"
    command: git config --global user.name "Packit Test Suite"
