---
- name: Install RPM dependencies for packit
  hosts: all
  tasks:
    - include_tasks: tasks/project-dir.yaml
    - include_tasks: tasks/generic-dnf-requirements.yaml
    - include_tasks: tasks/build-rpm-deps.yaml
    - name: Install python3-requre rpm
      dnf:
        name: python3-requre
      become: true
    - include_tasks: tasks/requre.yaml
