---
- name: Install RPM dependencies for packit
  hosts: all
  vars:
    project_dir: "{{ playbook_dir }}/.."
  tasks:
    - include_tasks: tasks/generic-dnf-requirements.yaml
    - include_tasks: tasks/build-rpm-deps.yaml
    - include_tasks: tasks/ogr-master.yaml
