---
- name: Install dependencies for packit tests
  hosts: all
  tasks:
    - ansible.builtin.include_tasks: tasks/project-dir.yaml
    - ansible.builtin.include_tasks: tasks/rpm-test-deps.yaml
    - ansible.builtin.include_tasks: tasks/ogr.yaml
    - ansible.builtin.include_tasks: tasks/specfile.yaml
    - ansible.builtin.include_tasks: tasks/sandcastle.yaml
    - ansible.builtin.include_tasks: tasks/centpkg.yaml
    - ansible.builtin.include_tasks: tasks/centos-packager.yaml
    # To (re-)generate tests_recording/test_data/
    - ansible.builtin.include_tasks: tasks/requre.yaml
    - name: Install pre-commit
      ansible.builtin.pip:
        name: pre-commit
