---
- name: This is a recipe for how to run packit tests
  hosts: all
  tasks:
    - include_tasks: tasks/project-dir.yaml
    - include_tasks: tasks/rpm-test-deps.yaml
    - include_tasks: tasks/install-packit.yaml
    - include_tasks: tasks/sandcastle.yaml
    - name: Run unit, integration and functional tests
      command: make check
      args:
        chdir: "{{ project_dir }}"
