---
- name: Install RPM dependencies for packit.
  hosts: all
  tasks:
    - include_tasks: tasks/generic-dnf-requirements.yaml
    - include_tasks: tasks/build-rpm-deps.yaml
    - include_tasks: tasks/requre-master.yaml
