---
- name: This is a recipe for how to run packit tests
  hosts: all
  tasks:
  - include_tasks: tasks/zuul-project-setup.yaml
  - include_tasks: tasks/rpm-test-deps.yaml
  - include_tasks: tasks/sandcastle-master.yaml
  - include_tasks: tasks/install-packit.yaml
  - include_tasks: tasks/configure-git.yaml
  - name: Run session recorded tests
    command: make check TESTS_TARGET=tests/session_recording
    args:
      chdir: '{{ project_dir }}'
