---
- name: Install dependencies for PIP packit.
  hosts: all
  tasks:
  - name: Install generic RPM packages
    dnf:
      name:
      - make
      - git
      - dnf-utils
      - python3-pip
    become: true
  - name: Install specific RPMs to be able to use clean PIP installation
    dnf:
      name:
      - krb5-devel
      - gcc
      - python3-devel
    become: true

  - name: Pip install ogr from master
    pip:
      name: git+https://github.com/packit-service/ogr
    become: true
