---
- name: pip install packit deps with ogr & requre
  hosts: all
  tasks:
    - include_tasks: tasks/generic-dnf-requirements.yaml
    - include_tasks: tasks/python-compile-deps.yaml
    - include_tasks: tasks/ogr.yaml
    - include_tasks: tasks/requre.yaml
    - include_tasks: tasks/sandcastle.yaml
