---
- name: This is a recipe for how to run packit tests
  hosts: all
  tasks:
    - ansible.builtin.include_tasks: tasks/project-dir.yaml
    - ansible.builtin.include_tasks: tasks/rpm-test-deps.yaml
    - ansible.builtin.include_tasks: tasks/install-packit.yaml
    - ansible.builtin.include_tasks: tasks/sandcastle.yaml
    - name: Run session recorded tests
      ansible.builtin.command: make check TEST_TARGET=tests_recording
      environment:
        REQURE_MODE: read
      args:
        chdir: "{{ project_dir }}"
