---
- name: Run pre-commit
  hosts: all
  tasks:
    - include_tasks: tasks/zuul-project-setup.yaml
    - name: Install git
      dnf:
        name:
          - git-core
          - python36
          - pre-commit
      become: true
      tags:
        - stop-layering

    - name: Run 'pre-commit install' to set up git hook scripts
      command: pre-commit install
      args:
        chdir: "{{ project_dir }}"

    - name: Run pre-commit
      command: pre-commit run --all-files
      args:
        chdir: "{{ project_dir }}"
