---
- name: Install dependencies for packit.
  hosts: all
  tasks:
  - include_tasks: tasks/generic-dnf-requirements.yaml
  - include_tasks: tasks/python-compile-deps.yaml
  - include_tasks: tasks/ogr-from-master.yaml
  - include_tasks: tasks/requre-master.yaml
