---
- name: Check if we are not breaking packit-service
  hosts: all
  tasks:
    - set_fact:
        reverse_dir: "{{ ansible_user_dir }}/{{ zuul.projects['github.com/packit/packit-service'].src_dir }}"
    - include_tasks: tasks/packit-service-requirements.yaml
    - include_tasks: tasks/install-packit-service.yaml
    - include_tasks: tasks/install-packit.yaml
    - name: Run unit, integration tests
      command: make check
      args:
        chdir: "{{ reverse_dir }}"
