---
- name: This is a recipe for how to run packit tests
  hosts: all
  tasks:
  - include_tasks: tasks/zuul-project-setup.yaml
  - name: Install test rpm dependencies
    dnf:
      name:
      - python3-flexmock
      - python3-pytest
      - python3-pytest-cov
      state: present
    become: true

  - name: Pip install sandcastle, our sandboxing tech (needed when running as a service)
    pip:
      name: git+https://github.com/packit-service/sandcastle
    become: true

  - name: Install packit from {{ project_dir }}
    pip:
      name: '{{ project_dir }}'
    become: true

  - name: Run tests
    command: make check
    args:
      chdir: '{{ project_dir }}'
