#!/bin/bash
set -ex

test `printenv PACKIT_PROJECT_VERSION` = "2.41"
# just make sure it is set
printenv PACKIT_PROJECT_COMMIT
test `printenv PACKIT_PROJECT_ARCHIVE` = "snapd-2.41.tar.gz"

p="packaging/fedora"

no_vendor="$(ls -1 ./packaging/fedora/*.no-vendor.tar.xz | xargs basename)"
vendor="$(ls -1 ./packaging/fedora/*.only-vendor.tar.xz | xargs basename)"

sed -i $p/snapd.spec -e "s/https.*no-vendor.tar.xz/$no_vendor/"
sed -i $p/snapd.spec -e "s/https.*only-vendor.tar.xz/$vendor/"
