name: Rebuild & push images
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-n-push:
    # To not run in forks
    if: github.repository_owner == 'packit'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: Containerfile
            image: packit

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Install QEMU dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Build Image
        id: build-image
        # https://github.com/marketplace/actions/buildah-build
        uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2
        with:
          dockerfiles: ${{ matrix.dockerfile }}
          image: ${{ matrix.image }}
          tags: latest
          archs: amd64, arm64
          oci: true

      - name: Push To Quay
        # https://github.com/marketplace/actions/push-to-registry
        uses: redhat-actions/push-to-registry@5ed88d269cf581ea9ef6dd6806d01562096bee9c # v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/packit
          username: ${{ secrets.QUAY_IMAGE_BUILDER_USERNAME }}
          password: ${{ secrets.QUAY_IMAGE_BUILDER_TOKEN }}
