name: Check release notes

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

check_release_notes:
  runs-on: ubuntu-latest
  steps:
    - name: Check
      uses: packit/.github/workflows/check-release-notes.yml@main
      with:
        description: ${{ github.event.pull_request.body }}
        placeholder: "Packit now supports automatic ordering of ☕ after all checks pass."
