name: Move new issues into the Kanban board

on:
  issues:
    types: [opened]

jobs:
  add-new-issue-to-the-kanban-board:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/packit/projects/7
          github-token: ${{ secrets.RELEASEBOT_GITHUB_TOKEN }}
