name: Move new issues into the Kanban board

on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: "Packit Kanban Board"
          column: new
          repo-token: ${{ secrets.RELEASEBOT_GITHUB_TOKEN }}
